### PR TITLE
Remove the int from cache function

### PR DESCRIPTION
**Pull request by Snodvod**
I tried to use your package, got an error that your code expected an int somewhere. No need for that, without the 'int' it's working properly.

### CODE REVIEW

**Comment by jpmurray** [comment]
Thanks for that @Snodvod , can you tell me exactly where you got that error and how you where using it?

I'm type hinting `int` so we're sure someone doesn't try to pass a float value for the cache time duration (I'm honestly not sure if Laravel accepts something like `1.5` (to cache for one and a half minute), hence the type hint.

**Comment by jpmurray** [comment]
I actually just been reminded that type declaration is a PHP >= 7.0 thing. Since 5.6 is now at end of support, I won't be removing this, instead I updated composer dependencies so it reflects that PHP should be at least a 7.0.

I encourage you to update to it, since it's end of support!

**Comment by Snodvod** [comment]
I see, didn't know that it was a new feature in php 7. I just think a lot of users will still be using php 5.6 for a long time... But maybe you're right and should we encourage to use 7 ;)

**Comment by jpmurray** [comment]
Yeah, there is so much to gain (just in speed, it's amazing!) in 7.0, you should do it! :)

**Pull request closed without merging**
